### ISSUE TITLE
Effects onoff or param change does not work unless App connected for LIVE

### ISSUE THREAD

**Issue by quiknick** [paulhamsh/SparkIO5#10]
Effects onoff or param change does not work unless App is connected affecting LIVE only, GO works fine.

**Comment by quiknick** [comment]
When app not connected message looks like this, and there is no effect onoff or param change.
```
Message: 415
Message: 415
Message: 415
Message: 415
Message: 415
Message: 415
Message: 415
Message: 415
```

When app connected message looks like this
```
Message: 115
Message: 415
Message: 415

Message: 415
Message: 115
Message: 415

Message: 115
Message: 415
Message: 415
```
When I disconnect the App and close the program, SparkBox keeps working with effect onoff or param change as expected. Message is the same as before app connected:
```
Message: 415
Message: 415
Message: 415
Message: 415
Message: 415
Message: 415
Message: 415
Message: 415
```

**Comment by paulhamsh** [comment]
Sorted
